# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
