# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 05:40
from __future__ import unicode_literals

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20170420_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=books.models.getProfilePath),
        ),
    ]
